"""
report_generator.py — Formats orchestrator output into structured JSON and Markdown.

Purely in-memory — no disk I/O, no local file saving.
Stateless and horizontally scalable by design.

Storage (PDF persistence, report history) is handled at the API layer
via Supabase when Pro tier is implemented.
"""

import math
from datetime import datetime, timezone


# ── Helpers ───────────────────────────────────────────────────────────────────

def _safe(val, fallback="N/A"):
    if val is None or val == "":
        return fallback
    try:
        if math.isnan(float(val)):
            return fallback
    except (TypeError, ValueError):
        pass
    return val


def _fmt_pct(val):
    try:
        return f"{float(val) * 100:.1f}%"
    except (TypeError, ValueError):
        return "N/A"


def _fmt_num(val, decimals=2):
    try:
        return round(float(val), decimals)
    except (TypeError, ValueError):
        return "N/A"


# ── JSON report ───────────────────────────────────────────────────────────────

def build_json_report(orchestrator_result: dict) -> dict:
    """
    Converts raw orchestrator output into a clean, frontend-ready JSON structure.
    This is what the FastAPI endpoint returns directly — nothing touches disk.
    """
    ticker  = orchestrator_result.get("ticker", "")
    company = orchestrator_result.get("company", ticker)
    signal  = orchestrator_result.get("signal", {})
    agents  = orchestrator_result.get("agent_results", {})
    report  = orchestrator_result.get("unified_report", "")
    elapsed = orchestrator_result.get("elapsed_seconds", 0)

    fund_raw   = agents.get("fundamentals", {}).get("raw", {})
    tech_raw   = agents.get("technicals",   {}).get("raw", {})
    sector_raw = agents.get("sector",       {}).get("raw", {})

    # ── Fundamentals ──
    fundamentals = {
        "pe_ratio":       _fmt_num(fund_raw.get("pe_ratio")),
        "forward_pe":     _fmt_num(fund_raw.get("forward_pe")),
        "eps":            _fmt_num(fund_raw.get("eps")),
        "roe":            _fmt_pct(fund_raw.get("roe")),
        "revenue_growth": _fmt_pct(fund_raw.get("revenue_growth")),
        "profit_margin":  _fmt_pct(fund_raw.get("profit_margin")),
        "debt_to_equity": _fmt_num(fund_raw.get("debt_to_equity")),
        "dividend_yield": _fmt_pct(fund_raw.get("dividend_yield")),
        "52w_high":       _safe(fund_raw.get("fifty_two_week_high")),
        "52w_low":        _safe(fund_raw.get("fifty_two_week_low")),
        "analyst_rating": _safe(fund_raw.get("analyst_rating")),
        "sector":         _safe(fund_raw.get("sector")),
    }

    # ── Technicals ──
    technicals = {
        "current_price":    _safe(tech_raw.get("current_price")),
        "change_pct":       _safe(tech_raw.get("change_pct")),
        "rsi_14":           _safe(tech_raw.get("rsi_14")),
        "rsi_zone":         _safe(tech_raw.get("rsi_zone")),
        "macd":             _safe(tech_raw.get("macd")),
        "macd_signal_line": _safe(tech_raw.get("macd_signal")),
        "macd_crossover":   _safe(tech_raw.get("macd_crossover")),
        "sma_50":           _safe(tech_raw.get("sma_50")),
        "sma_200":          _safe(tech_raw.get("sma_200")),
        "trend":            _safe(tech_raw.get("trend")),
        "bb_upper":         _safe(tech_raw.get("bb_upper")),
        "bb_lower":         _safe(tech_raw.get("bb_lower")),
        "signal_score":     _safe(agents.get("technicals", {}).get("score")),
    }

    # ── Sector peers ──
    peers = [
        {
            "name":       _safe(p.get("name")),
            "pe_ratio":   _fmt_num(p.get("pe_ratio")),
            "net_margin": _fmt_num(p.get("profit_margins")),
            "roe":        _fmt_num(p.get("roe")),
            "market_cap": _safe(p.get("market_cap")),
        }
        for p in sector_raw.get("peers", [])[:5]
    ]

    return {
        "meta": {
            "ticker":          ticker,
            "company":         company,
            "input_query":     orchestrator_result.get("input_query", ""),
            "user_prompt":     orchestrator_result.get("user_prompt", ""),
            "resolved_via":    orchestrator_result.get("resolution", {}).get("strategy", ""),
            "generated_at":    datetime.now(timezone.utc).isoformat(),
            "elapsed_seconds": elapsed,
            "disclaimer": (
                "This report is generated by AI for educational purposes only. "
                "It is NOT investment advice. Consult a SEBI-registered investment "
                "advisor before making any investment decisions."
            ),
        },
        "signal":         signal,
        "fundamentals":   fundamentals,
        "technicals":     technicals,
        "sector":         {"peers": peers},
        "unified_report": report,
        "agent_statuses": {
            name: data.get("status", "unknown")
            for name, data in agents.items()
        },
    }


# ── Markdown report ───────────────────────────────────────────────────────────

def build_markdown_report(json_report: dict) -> str:
    """
    Renders the JSON report as a Markdown string.
    In-memory only — caller decides what to do with it (stream, email, convert to PDF).
    """
    meta  = json_report["meta"]
    sig   = json_report["signal"]
    fund  = json_report["fundamentals"]
    tech  = json_report["technicals"]
    peers = json_report["sector"]["peers"]
    narr  = json_report["unified_report"]

    emoji = {
        "green": "🟢", "light-green": "🟡",
        "yellow": "🟡", "light-red": "🟠", "red": "🔴"
    }.get(sig.get("colour", ""), "⚪")

    scores = sig.get("component_scores", {})

    lines = [
        f"# {meta['company']} ({meta['ticker']}) — Stock Research Report",
        f"*Generated: {meta['generated_at']} | Educational use only*",
        "",
        "---",
        f"## {emoji} Composite Signal: {sig['label']}  _(Score: {sig['composite_score']} / 10)_",
        "",
        "| Dimension | Score |",
        "|-----------|-------|",
        f"| Fundamentals | {scores.get('fundamentals', 'N/A')} / 5 |",
        f"| Technicals   | {scores.get('technicals', 'N/A')} / 5 |",
        f"| Sentiment    | {scores.get('sentiment', 'N/A')} / 2 |",
        f"| Sector       | {scores.get('sector', 'N/A')} / 2 |",
        "",
        "---",
        "## 📋 Fundamentals",
        "",
        "| Metric | Value |",
        "|--------|-------|",
        *[f"| {k.replace('_', ' ').title()} | {v} |" for k, v in fund.items()],
        "",
        "---",
        "## 📈 Technicals",
        "",
        "| Indicator | Value |",
        "|-----------|-------|",
        *[f"| {k.replace('_', ' ').title()} | {v} |" for k, v in tech.items()],
        "",
        "---",
        "## 🏭 Sector Peers",
        "",
    ]

    if peers:
        lines += [
            "| Company | P/E | Net Margin | ROE | Market Cap |",
            "|---------|-----|-----------|-----|------------|",
            *[f"| {p['name']} | {p['pe_ratio']} | {p['net_margin']} | {p['roe']} | {p['market_cap']} |"
              for p in peers],
        ]
    else:
        lines.append("_Peer data not available._")

    lines += [
        "",
        "---",
        "## 🤖 AI Research Report",
        "",
        narr,
        "",
        "---",
        f"> ⚠️ **Disclaimer:** {meta['disclaimer']}",
    ]

    return "\n".join(lines)


# ── PDF export (Pro tier — in-memory bytes, no disk write) ────────────────────

def build_pdf_bytes(json_report: dict) -> bytes:
    """
    Generates a PDF in-memory and returns raw bytes.
    Caller streams it to the HTTP response or uploads to Supabase Storage.

    Requires: pip install weasyprint
    Pro-tier feature — call only after verifying subscription.
    """
    try:
        from weasyprint import HTML
    except ImportError:
        raise RuntimeError(
            "PDF export requires weasyprint. Install with: pip install weasyprint\n"
            "This is a Pro-tier feature."
        )

    md   = build_markdown_report(json_report)
    meta = json_report["meta"]

    html = f"""
    <html><head><meta charset="utf-8"><style>
      body {{ font-family: Arial, sans-serif; font-size: 13px; padding: 40px; color: #222; }}
      h1 {{ color: #1a1a2e; }} h2 {{ color: #16213e; border-bottom: 1px solid #ccc; padding-bottom: 4px; }}
      table {{ border-collapse: collapse; width: 100%; margin-bottom: 16px; }}
      th, td {{ border: 1px solid #ddd; padding: 6px 10px; text-align: left; font-size: 12px; }}
      th {{ background: #f0f0f0; }}
      blockquote {{ background: #fff8e1; border-left: 4px solid #f39c12; padding: 10px 16px; margin: 0; }}
      pre {{ white-space: pre-wrap; font-family: inherit; }}
    </style></head>
    <body><pre>{md}</pre></body></html>
    """

    # write_pdf() with no path arg returns bytes directly
    return HTML(string=html).write_pdf()


# ── Main entry point ──────────────────────────────────────────────────────────

def generate_report(orchestrator_result: dict) -> dict:
    """
    Converts orchestrator output → structured report. Purely in-memory.

    Returns:
        {
            "json_report": dict,      # returned by API endpoint
            "markdown":    str,       # for streaming or email
        }

    PDF bytes are generated separately via build_pdf_bytes() only on Pro tier.
    """
    json_report = build_json_report(orchestrator_result)
    markdown    = build_markdown_report(json_report)
    return {"json_report": json_report, "markdown": markdown}